In [16]:
x = np.zeros((3, 3), dtype=np.float)
print(x)
x[2,2]=1
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
import pandas as pd
from numpy import *
from pandas import Series,DataFrame
data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data',header=None)
data=data.drop([0,3,4,1,2],axis=1)
data.iloc[0,1]

0.33

In [23]:
import numpy as np
import pandas as pd
from numpy import *
from pandas import Series,DataFrame
data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data',header=None)
data=data.drop([0,3,4,1,2],axis=1)
x=data.loc[1].mean()

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [3]:
import numpy as np
import pandas as pd
from numpy import *
from pandas import Series,DataFrame
data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data',header=None)
data=data.drop([0,3,4,1,2],axis=1)


In [2]:
1+1=

SyntaxError: invalid syntax (<ipython-input-2-d2fa1a3ebe0a>, line 1)